### ISSUE TITLE
Build a python http server and simple iOS interface

### ISSUE THREAD

**Issue by xeodou** [Wiredcraft/test-mobile#1]
@WXGBridgeQ I remember you have some interesting on Python develop, so the main requirements in `Readme.md` under this repo. The special thing for you ,  you need use Python to build the HTTP server. 
I sent you an email, feel free ask question.

**Comment by WXGBridgeQ** [comment]
哥，我想哭。我是提了我有想学Python的兴趣，你还真叫我迅速自学Python啊。
那好吧，我也拼了，给我点时间。

**Comment by xeodou** [comment]
Done. Closing.
