### ISSUE TITLE
two questions about requirements.

### ISSUE THREAD

**Issue by simpzan** [Wiredcraft/test-mobile#12]
1, my task is only QR-generator.md, or includes User-flow.md?
2, in QR-generator, the UI mock includes a qr-scan screen, but there's no mention of it in the text. Is it included? If so, I need detailed requirement of this feature, like what to do with the data read from qr-scan.

**Comment by makara** [comment]
1. Only QR
2. The scan thing is a nice-to-have. It's just one way to validate the QRcode you generate and ideally it should ask another API to validate it.

**Comment by simpzan** [comment]
I got it, I will try to include it. Thanks :)

**Comment by makara** [comment]
No problem. Closing.
