### ISSUE TITLE
three questions about server and client

### ISSUE THREAD

**Issue by MelonRice** [Wiredcraft/test-mobile#26]
@makara 
Hi, Because I am unfamiliar with the requirement of server development, I want to ask the following three questions:
1. Does the server have to connect to the database for data storage, or can just directly generate temporary data for client access
2. Is it necessary to provide a cloud service for public network access to the api, or just to localhost access?
3. Is there any requirement for the minSdkVersion support for android client?

**Comment by kuno** [comment]
@MelonRice 

Hi, I am Android developer here.
I assume that you were talking about the test `QR-generator.md` here. So here is some clarification.
1,  No need database
2, Not necessary, a local network is enough as long as devices were able to connect to the server
3, Up to you

**Comment by makara** [comment]
Actually everything up to you, however if you are making any decisions you should have good reasons, and you should write done a few words in your document.

(BTW is your avatar a picture of you? I kinda remember a different person :)

**Comment by MelonRice** [comment]
@kuno @makara Thank you! 
my avatar picture is my wife..   ^_^

**Comment by jhonny-me** [comment]
closing as not valid anymore.
