### ISSUE TITLE
Build a simple backend server and iOS application use react-native

### ISSUE THREAD

**Issue by xeodou** [Wiredcraft/test-mobile#3]
Hi @MyEvonne  

We want you build a simple backend server with whatever language you like, and build a simple iOS application with React-native. I know maybe it's difficult to you , but we also think it's a challenge to your self. If it's really to difficult to build a backend server for you, you can try the backend server under this repo https://github.com/WXGBridgeQ/ios-test

Good luck.

**Comment by WXGBridgeQ** [comment]
😓

**Comment by quentinberder** [comment]
Done, closing.
