### ISSUE TITLE
can't find news api

### ISSUE THREAD

**Issue by gaojian922188** [Wiredcraft/test-mobile#30]
"As a user on the home page,
When I focus on to the search bar
And enter search terms
Then I should see the corresponding news result lists based on the search terms real time"

I searched github api doc, but can't find some apis can return news. maybe I misunderstand what you mean, can you help me?

**Comment by jhonny-me** [comment]
sorry, there is a typo here, it should be 
`Then I should see the corresponding new result lists based on the search terms real time`, the list here refers to the user list. @gaojian922188

**Comment by gaojian922188** [comment]
thank you for replying.
