### ISSUE TITLE
About requirement.

### ISSUE THREAD

**Issue by JackyMR** [Wiredcraft/test-mobile#4]
Hi,I am not very sure about the requirement.Is it just the introduction of QR-generator.md,or includes the other one user-flow.md.

**Comment by xeodou** [comment]
@JackyYuanOne  Sorry for that, I haven't explain it clearly. Your task is only `QR-generator.md` and `user-flow.md` is another task which it's not for you.

**Comment by quentinberder** [comment]
@JackyYuanOne you can also join us on Slack to speak directly to us.

**Comment by JackyMR** [comment]
@xeodou   @quentinberder  Thanks,i get it and i am doing this.
