### ISSUE TITLE
About the product request,I have two questions.

### ISSUE THREAD

**Issue by 154034532** [Wiredcraft/test-mobile#57]
The first one is 
"As a user on the home page,
When I tap on a user item
Then I should see the user's details"
It means to jump a webview page with "html_url"?

The second is 
"As a user on the item details page,
Then I should see user's home page loaded with the home page URL"
It means to load the "html_url" in the web view?

**Comment by seazon** [comment]
@154034532 
- Jump to the second page, you can check the figma design
- User story updated.
