### ISSUE TITLE
Which platform should I build this app for? iOS, Android or both?

### ISSUE THREAD

**Issue by ryantbd** [Wiredcraft/test-mobile#7]
Hi @makara, I've just read through the requirements in `QR-generator.md`, `README.md`, and also the email. It turns out that I'm not clear about the platform for this task. Should I build this app for iOS, Android, or both platform?

**Comment by makara** [comment]
Hi @ryaneof, the email should've mentioned that you are required to use React Native so I guess the platform doesn't really matter? Choose whichever you like.

**Comment by ryantbd** [comment]
@makara All right. Since I don't have any Android device, I might choose the iOS platform. Otherwise, I have to borrow one from my friends for testing. 

I will finish the iOS app by next Monday. :D

**Comment by makara** [comment]
Thanks. Any questions just let me know. Closing.
