### ISSUE TITLE
why do we need a scan function?

### ISSUE THREAD

**Issue by jhonny-me** [Wiredcraft/test-mobile#9]
Since the QR-code is generated by API's return value,all i need is call the API,get data, generate QR. So in which part do i need the camera scan function? Or you mean scan QR from other device?

**Comment by xeodou** [comment]
Hi @jhonny-me, yes,  Part of the app is build a scanner, allow the app scan the QR-code from other devices.

**Comment by jhonny-me** [comment]
Ok, another question,should server refresh a different seed everytime iOS call API or the refresh would happen at a fixed explicit time. @xeodou

**Comment by xeodou** [comment]
@jhonny-me It would be better have a new seed for a period time.

**Comment by jhonny-me** [comment]
@xeodou I get it,thanks.
